<?php
/**
 * Created by PhpStorm.
 * User: Max
 * Date: 13.09.2017
 * Time: 18:14
 * Темплейты уникализации названия картинок на соответствующем языке. Default = eng, остальное по $language_id
 */
$uniq_tpls = array(
    'default' => array(
        0 =>
            array(' 2018 ', ' 2018 ', ' 2018 ', ' 2018 ', ' 2018 ', ' 2017 ', ' 2017 ', ' 2017 ', ' 2017 ', ' cute ', ' cute ', ' cute ', ' cute ', ' cute ', ' cute ', ' easy ', ' easy ', ' easy ', ' easy ', ' easy ', ' easy ', ' natural ', ' natural ', ' natural ', ' natural ', ' natural ', ' natural ', ' best ', ' best ', ' best ', ' best ', ' best ', ' best ', ' new ', ' new ', ' new ', ' cool ', ' cool ', ' cool ', ' cool ', ' quick ', ' quick ', ' quick ', ' latest ', ' latest ', ' latest ', ' formal ', ' formal ', ' formal ', ' pretty ', ' popular ', ' modern ', ' nice ', ' trendy ', ' teens ', ' elegant ', ' trending ', ' hot ', ' everyday ', ' really ', ' really quick ', ' really easy ', ' really simple ', ' really nice ', ' really cool ', ' unique ', ' fast ', ' classic ', ' young ', ' fancy ', ' stylish ', ' awesome ', ' chic ', ' romantic ', ' sexiest ', ' gorgeous ', ' red carpet ', ' celebrity red carpet ', ' lazy ', ' easy lazy ', ' cute lazy ', ' overnight ', ' coolest ', ' cutest ', ' attractive ', ' youth '),
        1 =>
            array(' casual ', ' everyday ', ' super ', ' retro ', ' fancy ', ' mature ', ' stylish ', ' public ', ' hipster ', ' goddess ', ' perfect ', ' fifties ', ' hottest ', ' famous ', ' bohemian ', ' amazing ', ' romantic ', ' creative ', ' instagram ', ' mexican ', ' gorgeous ', ' ebony ', ' spanish ', ' sixties ', ' glamorous ', ' feminine ', ' ghetto ', ' easy lazy ', ' european ', ' glam ', ' recent ', ' gypsy ', ' universal ', ' sixteen ', 'you can afford ', ' affordable ', ' salon ', ' divine ', ' attractive ', ' the most sexy ', ' neat ', ' marvelous ', ' you desire ', ' bohemian ', ' catchy ', ' excellent ', ' naturally ', ' urban ', ' unique ', ' hottest ', ' brides ', ' romantic ', ' fabulous ', ' salon ', ' simplicity ', ' adorable ', ' convenient ', ' fashionable ', ' seductive ', ' fantastic ', ' mature ', ' graceful ', ' sweet ', ' cutest ', ' exquisite ', ' goddess ', ' favorite ', ' impressive ', ' outstanding ', ' elegance ', ' relaxed ', ' superb ', ' alluring ', ' exceptional ', ' coolest ', ' magnificent ')
    ),
    '0' => array(
        0 =>
            array(' 2018 ', ' 2018 ', ' 2018 ', ' 2018 ', ' 2018 ', ' 2017 ', ' 2017 ', ' 2017 ', ' 2017 ', ' bonito ', ' bonito ', ' bonito ', ' bonito ', ' bonito ', ' bonito ', ' fácil ', ' fácil ', ' fácil ', ' fácil ', ' fácil ', ' fácil ', ' natural ', ' natural ', ' natural ', ' natural ', 'naturais ', ' natural ', ' melhor ', ' melhor ', ' melhor ', ' melhor ', ' melhor ', ' melhor ', ' novo ', ' novo ', ' novo ', ' legal ', ' legal ', ' legal ', ' legal ', ' rápido ', ' rápido ', ' rápido ', ' mais recentes ', ' mais recentes ', ' mais recentes ', ' formal ', ' formal ', ' formal ', ' bonito ', 'popular ', ' moderno ', ' bom ', ' moda ', ' teens ', 'elegante ', ' tendências ', ' quente ', ' diário ', ' realmente ', ' mais rápido ', ' muito fácil ', ' muito simples ', ' muito bom ', ' muito legal ', ' único ', ' fast ', ' clássico ', ' jovem ', ' fantasia ', ' elegante ', ' incrível ', ' chique ', ' romântico ', ' mais sexy ', ' lindo ', ' tapete vermelho ', ' celebridade tapete vermelho ', 'preguiçoso ', ' fácil preguiçoso ', ' bonito preguiçoso ', ' noite ', ' mais legal ', ' mais bonito ', ' atraente ', ' a juventude '),
        1 =>
            array(' casual ', ' diário ', ' super ', ' retro ', ' fantasia ', ' madura ', ' elegante ', ' público ', ' hipster ', ' deusa ', ' perfeita ', ' cinquenta ', ' mais quentes ', ' famoso ', ' boêmia ', ' incrível ', ' romântico ', ' criativo ', ' instagram ', ' mexicano ', ' lindo ', ' ébano ', ' espanhol ', ' sessenta ', ' glamourosa ', 'feminino ', ' gueto ', ' fácil preguiçoso ', ' europeu ', ' glam ', ' recente ', ' cigano ', ' universal ', ' dezesseis ', 'você pode pagar ', ' acessíveis ', ' salão de beleza ', ' divino ', ' atraente ', ' mais sexy ', ' puro ', ' maravilhoso ', ' desejo ', ' boêmia ', ' cativantes ', 'excelente ', ' naturalmente ', ' urbano ', ' único ', ' mais quentes ', ' noivas ', ' romântico ', ' fabuloso ', ' salão de beleza ', ' simplicidade ', ' adorável ', ' conveniente ', ' moda ', ' sedutor ', ' fantástico ', ' madura ', ' graciosa ', ' doce ', ' mais bonito ', ' requintadas ', ' deusa ', ' favorito ', ' impressionante ', ' excelente ', ' elegância ', 'relaxado ', ' excelente ', ' sedutor ', ' excepcional ', ' mais legal ', ' magnífico ')
    ),
    '1' => array(
        0 =>
            array(' 2018 ', ' 2018 ', ' 2018 ', ' 2018 ', ' 2018 ', ' 2017 ', ' 2017 ', ' 2017 ', ' 2017 ', ' lindo ', ' lindo ', ' lindo ', ' lindo ', ' lindo ', ' lindo ', ' fácil ', ' fácil ', ' fácil ', ' fácil ', ' fácil ', ' fácil ', ' natural ', ' natural ', ' natural ', ' natural ', 'natural ', ' natural ', ' mejor ', ' mejor ', ' mejor ', ' mejor ', ' mejor ', ' mejor ', ' nuevo ', ' nuevo ', ' nuevo ', ' cool ', ' cool ', ' cool ', ' cool ', ' rápido ', ' rápido ', ' rápido ', ' último ', ' último ', ' último ', ' formal ', ' formal ', ' formal ', ' bastante ', 'popular ', ' moderno ', ' agradable ', ' de moda ', ' los adolescentes ', 'elegante ', ' tendencia ', ' caliente ', ' diario ', ' realmente ', ' muy rápido ', ' muy fácil ', ' simple ', ' muy bueno ', ' genial ', ' único ', ' rápido ', ' clásico ', ' joven ', ' fantasía ', ' estilo ', ' impresionante ', ' chic ', ' romántico ', ' sexy ', ' hermosa ', ' alfombra roja ', ' celebridades de la alfombra roja ', 'perezoso ', ' fácil perezoso ', ' lindo perezoso ', ' la noche ', ' más cool ', ' linda ', ' atractivo ', ' juventud '),
        1 =>
            array(' casual ', ' diario ', ' super ', ' retro ', ' fantasía ', ' maduro ', ' estilo ', ' público ', ' hipster ', ' diosa ', ' perfecto ', ' cincuenta ', ' más caliente ', ' famoso ', ' bohemio ', ' increíble ', ' romántico ', ' creativo ', ' instagram ', ' mexicana ', ' hermosa ', ' ébano ', ' español ', ' sesenta ', ' glamour ', 'femenino ', ' ghetto ', ' fácil perezoso ', ' europeo ', ' glamour ', ' reciente ', ' gitano ', ' universal ', ' dieciséis ', 'usted puede permitirse el lujo ', ' asequible ', ' salon ', ' divino ', ' atractivo ', ' más sexy ', ' limpio ', ' maravilloso ', ' deseo ', ' bohemio ', ' pegajoso ', 'excelente ', ' naturalmente ', ' urban ', ' único ', ' más caliente ', ' novias ', ' romántico ', ' fabuloso ', ' salon ', ' simplicidad ', ' adorable ', ' conveniente ', ' de moda ', ' seductora ', ' fantástico ', ' maduro ', ' elegante ', ' dulce ', ' linda ', ' exquisito ', ' diosa ', ' favorito ', ' impresionante ', ' pendiente ', ' elegancia ', 'relajado ', ' excelente ', ' seductor ', ' excepcional ', ' más cool ', ' magníficos '),
    ),
    '2' => array(
        0 =>
            array('2018 ', ' 2018 ', ' 2018 ', ' 2018 ', ' 2018 ', ' 2017 ', ' 2017 ', ' 2017 ', ' 2017 ', ' süß ', ' Niedlich ', ' süß ', ' Niedlich ', ' süß ', ' Niedlich ', ' leicht ', ' leicht ', ' leicht ', ' leicht ', ' leicht ', ' leicht ', ' Natur ', ' Natürliche ', ' Natur ', ' Natürliche ', 'Natur ', ' Natürliche ', ' best ', ' best ', ' best ', ' best ', ' best ', ' best ', ' new ', ' neu ', ' neu ', ' cool ', ' geil ', ' cool ', ' geil ', ' quick ', ' quick ', ' quick ', ' latest ', ' latest ', ' latest ', ' formales ', ' formales ', ' formales ', ' ziemlich ', 'beliebt ', ' modern ', ' schön ', ' trendy ', ' teens ', 'elegant ', ' trending ', ' hot ', ' Alltag ', ' wirklich ', ' flott ', ' wirklich leicht ', ' echt einfach ', ' wirklich nett ', ' wirklich cool ', ' unique ', ' schnell ', ' classic ', ' junge ', ' fancy ', ' stylish ', ' awesome ', ' chic ', ' romantisch ', ' sexy ', ' gorgeous ', ' red carpet ', ' celebrity red carpet ', 'faul ', ' einfach faul ', ' Niedlich faul ', ' Nacht ', ' coolsten ', ' süßeste ', ' attraktiv ', ' Jugend '),
        1 =>
            array(' casual ', ' Alltag ', ' super ', ' retro ', ' fancy ', ' Reifen ', ' stylish ', ' public ', ' hipster ', ' Göttin ', ' perfect ', ' fünfziger Jahre ', ' hottest ', ' berühmt ', ' Boheme ', ' amazing ', ' romantisch ', ' kreativ ', ' instagram ', ' mexican ', ' gorgeous ', ' Ebenholz ', ' Spanisch ', ' sechziger ', ' glamorous ', 'weiblich ', ' ghetto ', ' einfach faul ', ' europäischen ', ' glam ', ' letzten ', ' gypsy ', ' universal ', ' sechzehn ', 'Sie können es sich leisten ', ' günstige ', ' salon ', ' göttlicher ', ' attraktiv ', 'die meisten sexy ', ' ordentlich ', ' wunderbares ', ' Ihr Wunsch ', ' Boheme ', ' Ohrwurm ', 'hervorragend ', ' natürlich ', ' urban ', ' unique ', ' hottest ', ' Bräute ', ' romantisch ', ' Fabelhaft ', ' salon ', ' Einfachheit ', ' liebenswert ', ' bequem ', ' modisch ', ' verführerisch ', ' fantastisch ', ' Reifen ', ' anmutig ', ' süß ', ' süßeste ', ' exquisite ', ' Göttin ', ' Favorit ', ' beeindruckend ', ' hervorragend ', ' Eleganz ', 'entspannt ', ' hervorragend ', ' verführerisch ', ' ungewöhnlich ', ' coolsten ', ' magnificent '),
    ),
    '3' => array(
        0 =>
            array('2018 ', ' 2018 ', ' 2018 ', ' 2018 ', ' 2018 ', ' 2017 ', ' 2017 ', ' 2017 ', ' 2017 ', ' mignon ', ' mignon ', ' mignon ', 'mignon ', ' mignon', ' mignon ', "facile", "facile", "facile", "facile", "facile", "facile", "naturel", "naturel", "naturel", "naturel", "naturel", "naturel", "meilleur", "meilleur", "meilleur", "meilleur", "meilleur", " meilleur ", ' nouveau ', ' nouveau ', ' nouveau ', ' cool ', ' cool ', ' cool ', ' cool ', ' rapide ', ' rapide ', ' rapide ', 'plus tard ', ' de dernière minute ', ' de dernière minute ', "formel", "formel", "formel", "assez", ' populaire ', ' moderne ', ' nice ', ' trendy ', ' adolescents ', " élégante ", " tendance ", " chaud ", ' tous les jours ', ' vraiment ', ' très rapide ', ' très facile ', ' simple ', " vraiment sympa ", " vraiment cool ", " unique ", " rapide ", " classique ", " jeune ", ' fantaisie ', ' élégant ', ' génial ', ' chic ', ' romantique ', ' sexy ', ' magnifique ', ' tapis rouge ', ' célébrités tapis rouge ', 'paresseux ', ' facile paresseux ', ' mignon paresseux ', ' nuit ', ' plus cool ', ' mignon ', ' attractif ', ' la jeunesse '),
        1 =>
            array(' casual ', ' tous les jours ', ' super ', ' rétro ', ' fantaisie ', ' mature ', ' élégant ', ' public ', ' hipster ', ' déesse ', ' parfait ', ' cinquante ', ' les plus hot ', ' célèbres ', ' de la bohème ', ' extraordinaire ', ' romantique ', ' de créativité ', ' instagram ', ' mexicaine ', ' magnifique ', ' ébène ', ' espagnol ', ' soixante ', ' glamour ', 'féminin ', ' ghetto ', ' facile paresseux ', ' européenne ', ' glam ', ' récent ', ' gypsy ', ' universelle ', ' seize ', 'vous pouvez vous le permettre ', ' de abordable ', ' salon ', ' divin ', ' attrayants ', ' la plus sexy ', ' soigné ', ' merveilleuse ', ' vous désir ', ' de la bohème ', ' de accrocheur ', ' excellent ', ' naturellement ', ' urbain ', ' unique ', ' plus chaudes ', ' les épouses ', ' romantique ', ' fabuleux ', ' salon ', ' simplicité ', ' adorable ', ' pratique ', ' à la mode ', ' séduisant ', ' fantastique ', ' mature ', ' gracieux ', ' sweet ', ' mignon ', ' exquise ', ' déesse ', ' favoris ', ' impressionnante ', ' exceptionnelle ', ' elegance ', 'défaite ', ' superbe ', ' séduisant ', ' exceptionnel ', ' magnifique '),
    ),
    '4' => array(
        0 =>
            array('2018 ', ' 2018 ', ' 2018 ', ' 2018 ', ' 2018 ', ' 2017 ', ' 2017 ', ' 2017 ', ' 2017 ', ' carino ', ' carino ', ' carino ', ' carino ', ' carino ', ' carino ', ' facile ', ' facile ', ' facile ', ' facile ', ' facile ', ' facile ', ' naturale ', ' naturale ', ' naturale ', ' naturale ', 'naturale ', ' naturale ', ' migliore ', ' migliore ', ' migliore ', ' migliore ', ' migliore ', ' migliore ', ' nuovo ', ' nuovo ', ' nuovo ', ' cool ', ' cool ', ' cool ', ' cool ', ' veloce ', ' veloce ', ' veloce ', ' ultimo ', ' ultimo ', ' ultimo ', ' formale ', ' formale ', ' formale ', ' bella ', 'popolare ', ' moderna ', ' bella ', ' alla moda ', ' ragazzi ', 'elegante ', ' trend ', ' caldo ', 'tutti i giorni', '', ' veloce ', ' davvero facile ', ' davvero semplice ', ' veramente bello ', ' davvero cool ', ' unico ', ' veloce ', ' classico ', ' giovani ', ' fantasia ', ' elegante ', ' fantastico ', ' chic ', ' romantico ', ' sexy ', ' bellissima ', ' red carpet ', ' celebrity red carpet ', 'pigro ', ' facile pigro ', ' carino pigro ', ' la notte ', ' cool ', ' simpatico ', ' attraente ', ' giovani '),
        1 =>
            array(' casual ', ' tutti i giorni ', ' super ', ' retrò ', ' fantasia ', ' maturo ', ' elegante ', ' public ', ' hipster ', ' dea ', ' perfetto ', ' cinquanta ', ' top ', ' famosi ', ' bohemien ', ' incredibile ', ' romantico ', ' creative ', ' instagram ', ' messicano ', ' bellissima ', ' ebano ', ' spagnola ', ' anni sessanta ', ' glamour ', 'femminile ', ' ghetto ', ' facile pigro ', ' europeo ', ' glam ', ' recenti ', ' zingara ', ' universale ', ' sedici ', 'si può permettere ', ' accessibile ', ' bellezza ', ' divina ', ' attraente ', ' la più sexy ', ' pulito ', ' meraviglioso ', ' desiderio ', ' bohemien ', ' accattivante ', 'eccellente ', ' naturalmente ', ' urbano ', ' unico ', ' top ', ' spose ', ' romantico ', ' favoloso ', ' bellezza ', ' semplicità ', ' adorabile ', ' comoda ', ' moda ', ' seducente ', ' fantastico ', ' maturo ', ' grazioso ', ' dolce ', ' simpatico ', ' squisito ', ' dea ', ' preferiti ', ' impressionante ', ' sospeso ', ' eleganza ', 'rilassato ', ' superba ', ' seducente ', ' eccezionale ', ' cool ', ' magnifica '),
    ),
    '5' => array(
        0 =>
            array('2018 ', ' 2018 ', ' 2018 ', ' 2018 ', ' 2018 ', ' 2017 ', ' 2017 ', ' 2017 ', ' 2017 ', ' schattig ', ' schattig ', ' schattig ', ' schattig ', ' schattig ', ' schattig ', ' gemakkelijk ', ' gemakkelijk ', ' gemakkelijk ', ' gemakkelijk ', ' gemakkelijk ', ' gemakkelijk ', ' natuurlijk ', ' natuurlijk ', ' natuurlijk ', ' natuurlijk ', 'natuurlijk ', ' natuurlijk ', ' beste ', ' mooiste ', ' beste ', ' mooiste ', ' beste ', ' mooiste ', ' nieuw ', ' nieuw ', ' nieuw ', ' cool ', ' cool ', ' cool ', ' cool ', ' snel ', ' snel ', ' snel ', ' nieuwste ', ' nieuwste ', ' nieuwste ', ' formeel ', ' formeel ', ' formeel ', ' mooi ', 'populair ', ' modern ', ' mooi ', ' trendy ', ' tieners ', 'elegant ', ' trending ', ' warm ', 'alledaags', ' als echt ', ' erg snel ', ' echt makkelijk ', ' heel eenvoudig ', ' echt leuk ', ' heel cool ', ' uniek ', ' snel ', ' classic ', ' jong ', ' zin ', ' stijlvol ', ' awesome ', ' chique ', ' romantisch ', ' sexy ', ' prachtig ', ' rode loper ', ' celebrity red carpet ', 'lui ', ' easy lazy ', ' leuke lui ', ' overnachten ', ' coolste ', ' leukste ', ' aantrekkelijk ', ' jeugd '),
        1 =>
            array(' casual ', 'alledaags ', ' als super ', ' retro ', ' zin ', ' volwassen ', ' stijlvol ', ' publiek ', ' hipster ', ' godin ', ' perfect ', ' vijftig ', ' heetste ', ' beroemd ', ' bohemian ', ' geweldig ', ' romantisch ', ' creatief ', ' instagram ', ' mexicaanse ', ' prachtig ', ' ebony ', ' spaans ', ' de zestiger jaren ', ' glamour ', 'vrouwelijk ', ' ghetto ', ' easy lazy ', ' europees ', ' glam ', ' recent ', ' gypsy ', ' universeel ', ' zestien ', 'je kunt veroorloven ', ' betaalbaar ', ' salon ', ' het goddelijke ', ' aantrekkelijk ', ' de meest sexy ', ' een nette ', ' geweldig ', ' verlangen ', ' bohemian ', ' catchy ', 'uitstekend ', ' natuurlijk ', ' urban ', ' uniek ', ' heetste ', ' bruiden ', ' romantisch ', ' fantastisch ', ' salon ', ' eenvoud ', ' schattig ', ' handig ', ' modieus ', ' verleidelijk ', ' fantastisch ', ' volwassen ', ' sierlijk ', ' zoet ', ' leukste ', ' uitmuntend ', ' godin ', ' favoriet ', ' indrukwekkend ', ' outstanding ', ' elegance ', 'ontspannen ', ' fantastisch ', ' aantrekkelijk ', ' bijzonder ', ' coolste ', ' prachtig '),
    ),
    '6' => array(
        0 =>
            array('2018 ', ' 2018 ', ' 2018 ', ' 2018 ', ' 2018 ', ' 2017 ', ' 2017 ', ' 2017 ', ' 2017 ', ' søde ', ' sød ', ' sød ', ' sød ', ' sød ', ' sød ', ' let ', ' let ', ' let ', ' let ', ' let ', ' let ', ' naturlige ', ' naturlige ', ' naturlige ', ' naturlige ', 'naturlige ', ' naturlige ', ' bedste ', ' bedste ', ' bedste ', ' bedste ', ' bedste ', ' bedste ', ' ny ', ' ny ', ' ny ', ' cool ', ' cool ', ' cool ', ' cool ', ' hurtig ', ' hurtig ', ' hurtig ', ' nyeste ', ' nyeste ', ' nyeste ', ' formel ', ' formel ', ' formel ', ' smuk ', 'populære ', ' moderne ', ' flot ', ' trendy ', ' teenagere ', 'elegant ', ' tendenser ', ' hot ', ' everyday ', ' rigtig ', ' virkelig hurtig ', 'virkelig nemt", " virkelig enkel ', ' virkelig godt ', ' virkelig cool ', ' unik ', ' fast ', ' classic ', ' unge ', ' fancy ', ' elegant ', ' fantastisk ', ' smarte ', ' romantiske ', ' sexede ', ' smukke ', ' red carpet ', ' celebrity red carpet ', 'dovne ', ' let dovne ', ' søde dovne ', ' overnight ', ' fedeste ', ' killinger ', ' attraktiv ', ' unge '),
        1 =>
            array(' afslappet ', ' everyday ', ' super ', ' retro ', ' fancy ', ' gamle ', ' elegant ', ' det offentlige ', ' hipster ', ' gudinde ', ' perfekt ', ' halvtredserne ', ' hotteste ', ' berømte ', ' boheme ', ' fantastisk ', ' romantiske ', ' kreative ', ' instagram ', ' mexicanske ', ' smukke ', ' ebony ', ' spansk ', ' tresserne ', ' glamourøse ', 'feminine ', ' ghetto ', ' let dovne ', ' europa ', ' glam ', ' seneste ', ' sigøjner ', ' universelle ', ' seksten ', 'du kan ikke råd til ', ' billig ', ' salon ', ' guddommelig ', ' attraktiv ', ' den mest sexede ', ' pæn ', ' vidunderlig ', ' du ønske ', ' boheme ', ' catchy ', 'fremragende ', ' naturligt ', ' urban ', ' unik ', ' hotteste ', ' brude ', ' romantiske ', ' fremragende ', ' salon ', ' enkelhed ', ' sød ', ' praktisk ', ' fashionable ', ' forførende ', ' fantastisk ', ' gamle ', ' elegant ', ' sød ', ' killinger ', ' udsøgte ', ' gudinde ', ' favorit ', ' imponerende ', ' fremragende ', ' elegance ', 'afslappet ', ' fantastisk ', ' dragende ', ' enestående ', ' fedeste ', ' storslået '),
    ),
    '7' => array(
        0 =>
            array('2018 ', ' 2018 ', ' 2018 ', ' 2018 ', ' 2018 ', ' 2017 ', ' 2017 ', ' 2017 ', ' 2017 ', ' söt ', ' söt ', ' söt ', ' söt ', ' söt ', ' söt ', ' enkel ', ' enkel ', ' enkel ', ' enkel ', ' enkel ', ' enkel ', ' naturlig ', ' naturlig ', ' naturlig ', ' naturlig ', 'naturlig ', ' naturlig ', ' bästa ', ' bästa ', ' bästa ', ' bästa ', ' bästa ', ' bästa ', ' ny ', ' ny ', ' ny ', ' cool ', ' cool ', ' cool ', ' cool ', ' snabbt ', ' snabbt ', ' snabbt ', ' senaste ', ' senaste ', ' senaste ', ' formella ', ' formella ', ' formella ', ' vacker ', 'populära ', ' modern ', ' bra ', ' trendiga ', ' teens ', 'elegant ', ' trend ', ' hot ', ' vardagliga ', ' riktigt ', 'riktigt snabb ', 'verkligen lätt', ' verkligen ', "riktigt nice", "really cool", "unik", "snabb", ' den klassiska ', ' ung ', ' fancy ', ' snygg ', ' häftigt ', ' chic ', ' romantisk ', ' sexigaste ', ' vacker ', ' röda mattan ', 'kändis röda mattan", "lata", "lätt lata", " söt lat ', ' natten ', ' coolaste ', ' sötaste ', ' attraktiva ', ' ungdom '),
        1 =>
            array(' casual ', ' vardagliga ', ' super ', ' retro ', ' fancy ', ' gammal ', ' snygg ', ' allmän ', ' hipster ', ' gudinna ', ' perfekt ', ' fifties ', ' hetaste ', ' känd ', ' bohemian ', ' otroligt ', ' romantisk ', ' kreativa ', ' instagram ', ' mexikanska ', ' vacker ', ' ebony ', ' spanska ', ' talet ', ' glamorösa ', 'feminina ', ' ghetto ', ' lätt lat ', ' eu ', ' glam ', ' senaste ', ' zigenare ', ' universell ', ' sexton ', ' kan du ha råd ', ' prisvärt ', ' salong ', ' gudomlig ', ' attraktiva ', ' den mest sexiga ', ' snygg ', ' underbara ', ' du önskar ', ' bohemian ', ' catchy ', 'utmärkt ', ' naturligt ', ' urban ', ' unik ', ' hetaste ', ' brudar ', ' romantisk ', ' utmärkt ', ' salong ', ' enkelhet ', ' gulliga ', ' bekvämt ', ' på modet ', ' förförande ', ' fantastiskt ', ' gammal ', ' behaglig ', ' söt ', ' sötaste ', ' utsökt ', ' gudinna ', ' favorit ', ' imponerande ', ' olösta ', ' elegans ', ' avkopplande ', ' utmärkt ', ' lockande ', ' i undantagsfall ', ' coolaste ', ' magnifikt '),
    ),
    '8' => array(
        0 =>
            array('2018 ', ' 2018 ', ' 2018 ', ' 2018 ', ' 2018 ', ' 2017 ', ' 2017 ', ' 2017 ', ' 2017 ', ' söpö ', "söpö", "söpö", "söpö", "söpö", "söpö", "helppo", "helppo", "helppo", "helppo", "helppo", "helppo", "luonnollinen", "luonnollinen", "luonnollinen", "luonnollinen", "luonnollinen", "luonnollinen", "paras", "paras", "paras", "paras", "paras", "paras", "uusi", "uusi", "uusi", "cool", "cool", "cool", "cool", ' nopeasti ', ' nopeasti ', ' nopeasti ', ' uusin ', ' uusin ', ' uusin ', ' virallisen ', ' virallisen ', ' virallisen ', ' aika ', 'suosittu ', ' moderni ', ' mukava ', ' trendikäs ', ' teini ', 'tyylikäs ', ' trendit ', ' kuuma ', ' arjen ', ' todella ', ' nopeasti ', ' helppoa ', ' yksinkertainen ', ' mukava ', ' tosi cool ', ' ainutlaatuinen ', ' nopeasti ', ' klassikko ', ' nuori ', ' hieno ', ' tyylikäs ', ' mahtavia ', ' chic ', ' romanttinen ', ' seksikkäin ', ' ihana ', ' punainen matto ', ' julkkis punainen matto ', 'laiska ', ' helppoa laiska ', ' söpö laiska ', ' hetkessä ', ' coolein ', ' kiva ', ' houkutteleva ', ' nuoriso '),
        1 =>
            array(' casual ', ' arjen ', ' super ', ' retro ', ' hieno ', ' kypsä ', ' tyylikäs ', ' julkinen ', ' hipster ', ' jumalatar ', ' täydellinen ', ' fifties ', ' kuumin ', ' kuuluisa ', ' boheemi ', ' hämmästyttävä ', ' romanttinen ', ' luovaa ', ' instagram ', ' meksikon ', ' ihana ', ' musta ', ' espanja ', ' sixties ', ' lumoava ', 'naisellinen ', ' ghetto ', ' helppoa laiska ', ' euroopan ', ' glam ', ' viimeisimmät ', ' mustalainen ', ' yleinen ', ' kuusitoista ', 'varaa ', ' edullinen ', ' salonki ', ' jumalallinen ', ' houkutteleva ', ' kaikkein seksikäs ', ' siisti ', ' ihmeellinen ', ' halu ', ' boheemi ', ' tarttuva ', 'erinomainen ', ' luonnollisesti ', ' kaupunki ', ' ainutlaatuinen ', ' kuumin ', ' morsian ', ' romanttinen ', ' upea ', ' salonki ', ' yksinkertaisuus ', ' ihana ', ' kätevä ', ' muodikas ', ' houkutteleva ', ' mahtavia ', ' kypsä ', ' siro ', ' makea ', ' kiva ', ' hieno ', ' jumalatar ', ' suosikki ', ' vaikuttava ', ' erinomainen ', ' tyylikkyys ', 'rento ', ' loistava ', ' houkutteleva ', ' poikkeuksellinen ', ' coolein ', ' upea '),
    ),
    '9' => array(
        0 =>
            array('2018 ', ' 2018 ', ' 2018 ', ' 2018 ', ' 2018 ', ' 2017 ', ' 2017 ', ' 2017 ', ' 2017 ', ' roztomilý ', 'roztomilý ', 'roztomilý ', 'roztomilý ', 'roztomilý ', 'roztomilý ', 'easy ', 'easy ', 'easy ', 'easy ', 'easy ', 'easy ', 'přírodní ', 'přírodní ', 'přírodní ', 'přírodní ', 'přírodní ', 'přírodní ', 'nejlepší ', 'nejlepší ', 'nejlepší ', 'nejlepší ', 'nejlepší ', 'nejlepší ', 'nový ', 'nová ', 'nové ', 'cool ', 'v pohodě ', 'cool ', 'v pohodě ', 'rychlý ', 'rychlý ', 'rychlý ', 'poslední ', 'poslední ', 'poslední ', 'formální ', 'formální ', 'formální ', ' pěkně ', 'populární ', ' moderní ', ' nice ', ' trendy ', ' mládež ', 'elegantní ', ' trendy ', ' horká ', ' každý den ', ' opravdu ', 'opravdu rychlá ', 'moc snadný ', 'opravdu jednoduché ', 'opravdu pěkné ', ' je opravdu cool ', ' jedinečný ', ' rychlé ', ' klasický ', ' mladý ', ' chuť ', ' stylový ', ' super ', ' elegantní ', ' romantické ', ' sexy ', ' krásný ', ' red carpet ', ' celebrity red carpet ', 'líný ', ' snadné líný ', ' roztomilý líný ', ' noc ', ' nejlepší ', 'nejroztomilejší ', 'atraktivní ', 'mládež'),
        1 =>
            array(' casual ', ' každodenní ', ' super ', ' retro ', ' chuť ', ' zralé ', ' stylový ', ' public ', ' hipster ', ' bohyně ', ' perfektní ', ' padesátky ', ' nejžhavější ', ' slavný ', ' český ', ' úžasný ', ' romantické ', ' tvůrčí ', ' instagram ', ' mexická ', ' krásný ', ' ebony ', ' španělština ', ' šedesátá léta ', ' okouzlující ', 'ženský ', ' ghetta ', ' snadné líný ', ' european ', ' glam ', ' poslední ', ' cikán ', ' univerzální ', ' šestnáct ', 'může dovolit ', ' dostupné ', ' salon ', ' božské ', ' atraktivní ', ' sexy ', ' čistý ', ' úžasné ', ' touha ', ' český ', ' chytlavé ', ' vynikající ', ' přirozeně ', ' městský ', ' jedinečný ', ' nejžhavějších ', ' nevěsty ', ' romantické ', ' pohádkové ', ' salon ', ' jednoduchost ', ' roztomilý ', ' pohodlné ', ' módní ', ' svůdnou ', ' fantastické ', ' zralé ', ' elegantní ', ' sladké ', ' nejhezčí ', ' nádherné ', ' bohyně ', ' favorit ', ' působivé ', ' vynikající ', ' elegance ', 'uvolněná ', ' krásný ', ' svůdnou ', ' výjimečné ', ' nejlepší ', ' nádherné '),
    ),
//    '10' => array(
//        0 =>
//            array(),
//        1 =>
//            array(),
//    ),
//    '11' => array(
//        0 =>
//            array(),
//        1 =>
//            array(),
//    ),
//    '12' => array(
//        0 =>
//            array(),
//        1 =>
//            array(),
//    )
);